k21971/EvilHack

src/artifact.c
src/do_wear.c
src/makemon.c
src/mplayer.c
src/objnam.c
src/read.c
src/trap.c

A handful of typos, plus some fixes related to DSM messages and monsters generating with hated materials. The changes to mplayer.c and trap.c were a result of my being confused by the indentation near the end of the modified sections; there are no changes to the logic, but the whitespace should now be consistent with the rest of their respective files.

Minor fixes

---

src/hack.c

Was a bug introduced when boulders stacked (which was intended to make quivering/firing for giants easier).

Don't push around stacks of boulders as one

---

src/mon.c

Moves the resurrection process to dmonsfree, and surpresses killed notifications once she's been killed the first time. It will still break the messages for "the arrows hit kathryn"/etc., but it won't print "kathryn is defeated!" again. This uses the achievement for killing her to track, rather than her vital status.

Make the Ice Queen not aggro on multihits

---

src/mon.c

Was in mondead(), should have been in xkilled(), this should work.

Don't give the "Killed the Quest Leader" achievement if YOU didn't do it

---

include/extern.h
include/mondata.h
src/do_wear.c
src/makemon.c
src/mplayer.c
src/u_init.c

A couple really small changes mostly based on recent IRC conversations.  I wrote these commits a couple days ago but forgot to submit it as a PR.

Minor changes

---

include/extern.h
src/dogmove.c
src/dothrow.c
src/muse.c
src/pickup.c

Pets would stash items they would otherwise save, then drop the
container they put them into -- this refines the logic used to determine
whether an item is useful or not, and should also prevent pets from
dropping sacks/bags of holding.

Prevent pet from stashing useful items (unicorn horns, etc)

---

src/do_name.c
src/mon.c
src/shknam.c

- Hide racial adjective when hallucinating
- Set mon gender when applying M1_FEMALE, etc, race

minor erac fixes

---

README
src/pager.c

update contact info to reflect current IRC network host :)

update Freenode IRC refs to Libera Chat

---

include/display.h
include/extern.h
src/do_name.c
src/objnam.c
src/read.c

- Use racial adjectives in statue names
- Use racial glyphs for statues
- Use race to 'revive' aligned priest into zombie

Racial statues

---

include/mondata.h
src/dog.c
src/mkmaze.c
src/shk.c
src/uhitm.c
src/worn.c

Also simplify the way racial_foo macros are defined.

Expand racial_<mon> macro usage a bit

---

src/dogmove.c
src/muse.c

The 'muse restore ability' patch (PR #79) was taken out of the oven
before it was done baking and needed some followup.

Fix issues with monsters using restore ability

---

src/mcastu.c

Destroy armor cast against a monster would instantly destroy a piece of
armor, and could be resisted by high level monsters; destroy armor
against the hero would erode a piece of armor to a certain extent, and
then destroy it outright after that point.  Make destroy armor work the
same way vs a monster as it does vs the hero.

Make destroy armor vs mon match effect vs hero

---

dat/bogusmon.txt

nobody loves a mystery. especially not a mystery van.

reduce typo suspicions

---

dat/wizhelp
doc/Guidebook.mn
doc/Guidebook.tex
include/extern.h
src/apply.c
src/cmd.c
src/pray.c
src/spell.c
src/teleport.c

#wizspell allows casting any spell for 0 energy and nutrition at Expert skill with 100% success.

New wizard mode command: #wizspell (^s)

---

dat/tribute

Literally unplayable.
Line length does not seem to be a problem because there are some lines longer than this.

tribute: typo fix

---

src/allmain.c
src/apply.c
src/do_wear.c
src/dungeon.c
src/mhitu.c
src/minion.c
src/monst.c
src/objnam.c
src/potion.c
src/spell.c

A bunch of 1- or 2-liner bugs, usually only noticeable in edge cases. 
The only one I'm not certain should be called a bug is stunned/confused jumping, which wasn't exactly broken per se, but it was super weird that it was allowed.

Minor bugs

---

doc/evilhack-changelog.md
src/artifact.c
src/do_wear.c

On the EvilHack wiki I noticed it says it grants cold res.
This is my first PR, do I usually target the master branch?

Fix: Silver dragon scaled armor was not granting cold resistance.

---

src/trap.c
src/wield.c

Fix a few cases of destroying indestructible artifacts. Make spear traps hit monsters' steeds.Fix a case of granting benefits of alternate weapon when not twoweaponing.

A few more minor bugs

---

src/mklev.c
src/mkmap.c
src/sp_lev.c

Like lava, forges glow even in dark rooms. Also like lava, they can still be darkened magically.

Forges are always lit

---

include/extern.h
include/objclass.h
src/do.c
src/dogmove.c
src/eat.c
src/extralev.c
src/fountain.c
src/invent.c
src/makemon.c
src/mcastu.c
src/mkobj.c
src/mon.c
src/mplayer.c
src/muse.c
src/objnam.c
src/pray.c
src/quest.c
src/read.c
src/shknam.c
src/sp_lev.c
src/u_init.c
src/wield.c
src/zap.c

Address most of the weirdness stemming from allowing inherently fixed materials to be erodeproofed.

fixed fixing fixes

---

doc/evilhack-changelog.md
src/pickup.c

Also, stone the blind&barehanded, as #looting does.

Allow tipping into containers on floor.

---

include/youprop.h

Caught an oversight from when the switch was made from gold dragons/their scales being sickness resistant to green.

Gold and green changes

---

src/steed.c

Spotted these while poking around for the usual wiki documentation.

very small spelling corrections

---

dat/quest.txt

First pass at druid quest text based on my limited knowledge of K2's intent.

Initial druid quest text.
